### ISSUE TITLE
Changing the color of the tiles

### ISSUE THREAD

**Issue by SeraphWedd** [nicoloridulfo/Conways-Game-of-Life-using-pyGame#3]
So, as I have tested, the `pg.surfarray.make_surface` takes a total of 128 inputs for different colors (ranging from 0 to 127). 0 is treated as black, 1 is blue, 2 is slightly lighter blue, and so on. You can check this too by substituting a test array for life.grid with this code:
```
array = np.zeros((32, 32)) #4 lines is 128
for y in range(32):
    for x in range(32):
        array[y][x] = 32*y + x
```
Then plugging it in for game_surf:
```
game_surf = pg.surfarray.make_surface(array)
```

You will see an interesting looking checkerboard filled with arrays of colors. So, if you want to make the image black and white again, I suggest you use 127 (for white), like this:

```
game_surf = pg.surfarray.make_surface(127 * life.grid)
```

**Comment by nicoloridulfo** [comment]
Currently it is multiplied by 255. I will change it! Thanks!
